### PR TITLE
Feature/handbook

### PR DESCRIPTION
**Pull request by 27Bslash6**
Adds new container to the docker build process: gcr.io/planet-4-151612/handbook

New container adds a script which is executed on container start to set appropriate permissions.

Also includes modifications to wp-config.php.tmpl, such that the Wordpress directive DISALLOW_FILE_MODS can be enabled / disabled by environment variable.  This variable is set to 'true' in the Wordpress container, and 'false' in the Handbook container.

### CODE REVIEW

**Comment by 27Bslash6** [comment]
The changes to wp-config.php.tmpl ( https://github.com/greenpeace/planet4-docker/blob/d50987e49dc7e3f2e1f8a881b4d932f6ac1df1bb/src/planet-4-151612/wordpress/wp-config.php.tmpl#L39 ) reproduce functionality currently described by https://github.com/greenpeace/planet4-handbook/blob/develop/post_deploy_scripts/01-make-filesystem-writtable.sh

The script added to etc/my_init.d ( https://github.com/greenpeace/planet4-docker/pull/34/files#diff-d301f0e2f6b24f5717a06e4106661f1e ) reproduces funcitonality of https://github.com/greenpeace/planet4-handbook/blob/develop/post_deploy_scripts/01-make-filesystem-writtable.sh

I do have questions about whether it's actually necessary to set these permissions though, surely they're already writable by the application user?

Finally, these changes haven't been tested on any handbook containers yet.  @koyan if you could please run these tests ( perhaps by merging changes suggested in greenpeace/planet4-handbook#1 ) and confirm functionality

**Comment by koyan** [comment]
> I do have questions about whether it's actually necessary to set these 
> permissions though, surely they're already writable by the application user?
In the phppod until now, without this change, the php application could not write on those files. 

I would prefer a solution that would not require a different docker parent only for handbook, but I guess you know better. Testing the change on develop of handbook with the new parent now. (merged the planet4-handbook PR)

**Comment by koyan** [comment]
I have tested on the develop site of handbook it and it seems to be working: 
lang-files-writtable

**Comment by 27Bslash6** [comment]
> I would prefer a solution that would not require a different docker parent only for handbook, but I guess you know better. Testing the change on develop of handbook with the new parent now. (merged the planet4-handbook PR)

If you want to conditionally perform operations only for this use-case, and they need to occur on each container start, then I think this is the cleanest solution.  The /etc/my_init.d folder in the container is designed specificaly to bootstrap in this manner.

**Pull request merged**
