### PR TITLE
PLANET-5146: Modify composer wrapper execution conditions

### PR DESCRIPTION
**Pull request by lithrel**
Ref: https://jira.greenpeace.org/browse/PLANET-5146
Full explanation: https://gist.github.com/lithrel/f78fc62c09b1f63e715f1b0992cb3cbd
Should solve: https://github.com/greenpeace/planet4-docker-compose/issues/42

# Original issue
When we call `composer` in the `php-fpm` container, it is actually wrapped [in a shell script](https://github.com/greenpeace/planet4-docker/blob/master/src/planet-4-151612/php-fpm/bin/composer.sh) that first controls the user running the script and ownership of the `/app/source` directory. If it finds something wrong, it tries to correct it by chowning the whole directory.

Because of the usage of option `-n` and its comparison with `APP_USER` in a condition, this wrapper runs a full `chown` of `/app/source` on each call, even if dir owner is correct.

```console
# Condition $(ls -ldn . | awk '{print $3}') != "${APP_USER}"

root@f2ea70833ec6:/app/source# echo $APP_USER
app
root@f2ea70833ec6:/app/source# ls -ldn . | awk '{print $3}' # current condition
1000
root@f2ea70833ec6:/app/source# ls -ld . | awk '{print $3}' # fixed condition
app
```

You can reproduce this issue by running in your `planet4-docker-compose`:
```console
> make run
> eval $(make env)
> time docker-compose exec php-fpm sh -c "composer --version"
```
 It should take an unusual amount of time for this command.

## Other modifications

- Changed the `ls` target from `.` to `"${SOURCE_PATH}"` 
  It seems to be its only purpose, and might avoid problems if composer is ran from another place.
- Changed a `chown -R` to a `find ! -user app -exec chown -f`
  chown seems to be a costly operation, at least on a macOS system; doing a `find` first reduced execution time significantly (more than 50% on a basic test,  but shouldn't be that significant on linux).
- Made the chown silent
  I'm not sure this chown should throw any error, chown on a symlink not present yet or an innaccessible file is probably not a problem in this context. But it allowed me to find that problem, so maybe I should go back on this.

# Questions

- I wanted to go further and `chown app /app/bin/composer` so that we can call it with `--user app` in our docker-compose file and make it even faster and more coherent, but I can't do it during composer installation, [APP_USER does not exist yet](https://app.circleci.com/pipelines/github/greenpeace/planet4-docker/43/workflows/a4481955-428b-4ab9-850a-cc29283c88e7/jobs/7611). Is there a good place to do this ? 
- Would it make sense to run all composer calls with `$APP_USER`, in this script for example ? https://github.com/greenpeace/planet4-docker/blob/1edaf4d1d067229dd900c105d66bc137f04bddec/src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh#L218

# Testing

_An image should be built with those modifications._

No changes should be expected, except for faster run times on composer calls.

You can also experiment on the issue by reporting those modifications in your own container, by going in `make php-shell` and editing file `/app/bin/composer.sh`. Bench it by doing first a `time make nro-enable` for example, then apply modifications, and try it again. Add `set -x` at the beginning of the file to make it display all the commands it runs, make the chown verbose by adding a `-v` option to it.

### CODE REVIEW

**Comment by comzeradd** [comment]
Can you target `develop` first?

**Comment by 27Bslash6** [comment]
Nice fix, thanks.  I see no issue with executing a single chown in my_init on startup, but perhaps as its own script instead of piggy backing on the existing wp install?

Anything in `my_init.d/*` is executed, ref https://github.com/phusion/baseimage-docker#running_startup_scripts

**Comment by 27Bslash6** [comment]
Out of interest, what are the numbers benching this change?

**Comment by lithrel** [comment]
> Out of interest, what are the numbers benching this change?

I tried a few things in [this doc](https://gist.github.com/lithrel/f78fc62c09b1f63e715f1b0992cb3cbd), and comparing ubuntu and macOS it is clear that this will benefit mostly macOS, but for example on my macbookair 2020, I went from 2 minutes to 15 seconds on a command chaining 6 calls to composer; after playing with npm and generating far too many node_modules files, a simple `composer --version` would take up to 7 minutes instead of the usual sub 1 second.

> Nice fix, thanks. I see no issue with executing a single chown in my_init on startup, but perhaps as its own script instead of piggy backing on the existing wp install?

Good idea, thanks :)

**Comment by lithrel** [comment]
Fixed (in develop)

**Pull request closed without merging**
